<?php require(dirname(__FILE__) . '/header.php'); ?>

<div class="section">
<h2>A to Z</h2>
<p>Use the A to Z to find a programme by name.</p>
<?php require(dirname(__FILE__) . '/a-z.php'); ?>
</div>

<div class="section">
<h2>Categories</h2>
<p>
We categorise our programmes by <a href="genres">genre</a> and <a href="formats">format</a>. Browse these categories and discover current programmes of interest.
</p>
</div>

<?php require(dirname(__FILE__) . '/footer.php'); ?>
