<?php require(dirname(__FILE__) . '/header.php'); ?>

<div id="primary">

<div class="section">
<?php

	 if(isset($object->image))
	 {
		 writeLn('<p class="depiction"><img src="' . _e($object->image) . '"></p>');
	 }
?>
<p>
Video player would go here. When retrieving versions and selecting an
available location is implemented, at any rate.
</p>

<p><?php echo str_replace("\n", '<br>', _e($object->description)); ?></p>
</div>

</div>

<div id="secondary">

<?php

	 if(isset($object['series']))
	 {
		 
	 }
	 else if(isset($object['show']))
	 {
		 writeLn('<div class="section episode-position">');
		 if(isset($object->episodeNumber))
		 {
			 writeLn('<p>Episode ' . _e($object->episodeNumber) . ' of <a href="' . _e($app_root . $object['show']->relativeURI) . '">' . _e($object['show']->title) . '</a></p>');
		 }
		 else
		 {
			 writeLn('<p>An episode of <a href="' . _e($app_root . $object['show']->reltiveURI) . '">' . _e($object['show']->title) . '</a></p>');
		 }
		 writeLn('</div>');
	 }
?>

<?php require(dirname(__FILE__) . '/related-content.php'); ?>
</div>

<?php require(dirname(__FILE__) . '/footer.php');