<?php require(dirname(__FILE__) . '/header.php'); ?>

<div id="primary">

<div class="section">
<?php

	 if(isset($object->image))
	 {
		 writeLn('<p class="depiction"><img src="' . _e($object->image) . '"></p>');
	 }
?>
<p>
Video player would go here. When retrieving versions and selecting an
available location is implemented, at any rate.
</p>

<p><?php echo str_replace("\n", '<br>', _e($object->description)); ?></p>
</div>

</div>

<div id="secondary">

  <h2>Sidebar whatnots</h3>

<?php

	 if(isset($object['series']))
	 {
		 
	 }
	 else if(isset($object['show']))
	 {
		 writeLn('<div class="section episode-position">');
		 if(isset($object->episodeNumber))
		 {
			 writeLn('<p>Episode ' . _e($object->episodeNumber) . ' of <a href="' . _e($app_root . $object['show']->relativeURI) . '">' . _e($object['show']->title) . '</a></p>');
		 }
		 else
		 {
			 writeLn('<p>An episode of <a href="' . _e($app_root . $object['show']->reltiveURI) . '">' . _e($object['show']->title) . '</a></p>');
		 }
		 writeLn('</div>');
	 }
?>

<?php if(isset($object->genres))
{
?>
<div class="section genre-list tag-list">
<h3>Genres:</h3>
<ul>
<?php
foreach($object->genres as $genre)
{
	echo '<li><a href="' . _e($genre) . '">' . $genre . '</a></li>';
}
?>
</ul>
</div>
<?php } ?>

<?php if(isset($object->formats))
{
?>
<h3>Formats:</h3>
<ul>
<?php
foreach($object->formats as $format)
{
	echo '<li><a href="' . _e($format) . '">' . $format . '</a></li>';
}
?>
</ul>
<?php
}
?>

<?php if(isset($object->topics))
{
?>
<h3>Topics:</h3>
<ul>
<?php
foreach($object->topics as $topic)
{
	echo '<li><a href="' . _e($topic) . '">' . $topic . '</a></li>';
}
?>
</ul>
<?php
}
?>
</div>

<?php require(dirname(__FILE__) . '/footer.php');