<?php require(dirname(__FILE__) . '/header.php'); ?>

<div class="section">
<h2>A-Z</h2>
<?php require(dirname(__FILE__) . '/a-z.php'); ?>
</div>

<div class="section prog-list">

<ul>
<?php

	 while(($prog = $objects->next()))
	 {
		 echo '<li><a href="' . _e($app_root . $prog->relativeURI) . '">' . _e($prog->title) . '</a></li>';
	 }

?>
</ul>

<?php require(dirname(__FILE__) . '/footer.php');
		 