<?php require(dirname(__FILE__) . '/header.php'); ?>

<div class="section">
<?php

	 if(isset($object->image))
	 {
		 writeLn('<p class="depiction"><img src="' . _e($object->image) . '"></p>');
	 }
	 else
	 {
		 writeLn('<p>No depiction yet :(</p>');
	 }
?>

<p><?php echo str_replace("\n", '<br>', _e($object->description)); ?></p>
</div>

<?php if(isset($series))
{
?>
<div class="section">
	<h2>Series</h2>
	<ul>
<?php
		while(($obj = $series->next()))
		{
			echo '<li><a href="' . _e($app_root . $obj->relativeURI) . '">' . _e($obj->title) . '</a></li>';
		}
?>
	</ul>
</div>
<?php } ?>


<?php if(isset($episodes))
{
?>
<div class="section">
	<h2>Episodes</h2>
	<dl>
<?php
		while(($obj = $episodes->next()))
		{
			writeLn('<dt><a href="' . _e($app_root . $obj->relativeURI) . '">' . _e($obj->title) . '</a></dt>');
			writeLn('<dd>' . _e($obj->shortDescription) . '</dd>');
		}
?>
	</dl>
</div>
<?php } ?>

<?php require(dirname(__FILE__) . '/footer.php');